version: 2.1
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run: 
        name: Echo Test
        command: echo "Hello World"
  deploy:
    machine:
        image: circleci/classic:edge
    steps:
      - checkout
      - add_ssh_keys:
      - run: ssh ${USER_NAME}@${HOST_NAME} 'cd && git pull'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master