version: 2.1

jobs:
    build:
        docker:
            - image: alpine
        steps:
            - checkout
            - run:
                name: Echo Test
                command: echo "CircleCI Test"
    deploy:
        machine:
            image: circleci/classic:edge
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "2d:5d:42:7d:cc:5a:ca:7f:4c:eb:d8:0e:61:24:34:38"
            - run: 
                name: ssh
                command: ssh ${USER_NAME}@${HOST_NAME} 'cd /var/www/docker-laravel-task && git pull'

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: master